name: villager-refresh
version: '1.1 '
main: org.renwixx.vRefresh.VillagerRefresh
api-version: '1.12'
authors: [ Renwixx ]
description: Allows to ignore gamerule 'doDaylightCycle' for villager trades refresh.
website: https://github.com/renwixx/
commands:
  vrefresh:
    description: Command to control plugin VillagerRefresh.
    usage: /<command> reload | /<command> setInterval [minutes]
    tab-completer: org.renwixx.vRefresh.VillagerRefresh
permissions:
  villagerrefresh.commands:
    description: Allows using all /vrefresh commands.
    default: true